### ISSUE TITLE
SUpdate // ignore.list

### ISSUE THREAD

**Issue by Jonatxr** [TheShark34/S-Update#10]
Permissions ==> 777 sur ignore list
Versions de SUpdate + SUpdate server => 3.1
Pas de faute de frappe dans l'ignore.list
ligne ==> su.getServerRequester().setRewriteEnabled(true); ajoutée
Fichiers transférés via WINSCP
et pourtant ==> options.txt & splash.properties se font toujours override par SUpdate et à chaque nouveau lancement de launcher les options reviennent comme sur mes FTP, alors que j'aimerais avoir une config de base mais modifiables...
Merci pour l'aide, et ggwp pour tout ça même 3 ans après damn

**Comment by Litarvan** [comment]
Tu as probablement mis options.txt et splash.properties dans le dossier files/, si oui c'est normal, tu ne peux pas faire comme ça si tu veux pouvoir les modifier désolé :/

**Comment by Jonatxr** [comment]
Donc tu penses c'est pas possible de mettre un pack par défaut ect ?

**Comment by Litarvan** [comment]
Il faudrait que tu les mettes hors du dossier files/ et que tu les télécharges toi même, les gens font comme ça d'habitude, désolé S-Update n'est pas vraiment fait pour ça

**Comment by Jonatxr** [comment]
Arrête de t'excuser c'est déjà énorme de pouvoir faire un launcher en étant un full random x)
