### ISSUE TITLE
Bug de FileDeleter

### ISSUE THREAD

**Issue by DatPenguin** [TheShark34/S-Update#5]
Bonsoir ! Je suis en train de créer un launcher en suivant ton excellent tutoriel, mais j'ai bien peur d'avoir rencontré un bug de FileDeleter. En effet, il supprime systématiquement mon fichier login.properties, que j'utilise comme Saver, malgré le fait que je l'ai renseigné dans l'ignorelist. D'ailleurs, pour les autres fichiers présents dans cette liste, ils sont bien ignorés par FileDeleter. Est-ce un bug ?

Merci!

**Comment by Litarvan** [comment]
Il faut SUpdate 3.1 et non pas la 3.0, met aussi les permissions 777 sur l'ignore list, et vérifie que les majuscules correspondent

**Comment by DatPenguin** [comment]
Effectivement, le bug venait du 777. Merci !
