### ISSUE TITLE
Pic CPU important pendant "Listing the files"

### ISSUE THREAD

**Issue by ArthixFR** [TheShark34/S-Update#6]
Bonjour / Bonsoir,

J'utilise tes libs pour le laucher de mon serveur FeedTheBeast privé, et pendant que le launcher liste les fichiers mon CPU monte directement à 100% et reste bloqué d'ailleurs :/. Pour informations j'utilise la dernière version de S-Update soit la 3.1.0-BETA. Si t'as besoin de screens, ect demande moi :)

EDIT: J'ai l'impression que c'est a cause du nombre de fichiers à lister.

Merci d'avance.

**Comment by Litarvan** [comment]
SUpdate utilise le maximum de resource pour aller le plus rapidement possible, dans tous les cas c'était pas voulu et je sais pas pourquoi c'est ça, et puis oui il y a énormément des fichiers à lister donc forcément. J'y peux rien, c'est comme ça. Dans tous les cas ça dur pas longtemps

**Comment by ArthixFR** [comment]
Ça dure pas longtemps avec environ 2000 fichiers, mais quand j'ai ajouté un pack de textures avec plus de 48000 fichiers, j'ai laissé tourné le launcher environ 5 minutes et c'est resté sur "Listing the files" :/ M'enfin bref j'ai zippé le pack de textures et j'ai plus le soucis ! Merci quand même d'avoir pris le temps de me répondre :)
